package dependabot

import (
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

func writeConfig(configFile string, config *Config) error {
	err := os.MkdirAll(filepath.Dir(configFile), 0o755)
	if err != nil {
		return err
	}
	data, err := yaml.Marshal(config)
	if err != nil {
		return err
	}
	header := "# This file is autogenerated by the 'modulegen' tool.\n# Please look at the generator code when updating it.\n"
	data = append([]byte(header), data...)
	return os.WriteFile(configFile, data, 0o644)
}
