name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
template: |
    # What's Changed
    $CHANGES
categories:
  - title: ⚠️ Breaking Changes
    labels:
      - 'breaking change'
  - title: 🔒 Security
    labels:
      - 'security'
  - title: 🚀 Features
    labels:
      - 'enhancement'
      - 'feature'
  - title: 🐛 Bug Fixes
    labels:
      - 'bug'
  - title: 📖 Documentation
    labels:
      - 'documentation'
  - title: 🧹 Housekeeping
    labels:
      - 'chore'
      - 'test flakiness'
  - title: 📦 Dependency updates
    label: 'dependencies'
autolabeler:
  - label: 'breaking change'
    title:
      - '/^[a-z]+(\(.+\))?!\:/i'
  - label: 'security'
    title:
      - '/^security(\(.+\))?\:/i'
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?\:/i'
  - label: 'bug'
    title:
      - '/^(fix|bug)(\(.+\))?\:/i'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?\:/i'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?\:/i'
  - label: 'dependencies'
    title:
      - '/^deps(\(.+\))?\:/i'
