package dependabot

import (
	"os"

	"gopkg.in/yaml.v3"
)

func WriteConfig(configFile string, config *Config) error {
	data, err := yaml.Marshal(config)
	if err != nil {
		return err
	}
	header := "# This file is autogenerated by the modulegen code generator. Please look at the generator code when updating it.\n"
	data = append([]byte(header), data...)
	return os.WriteFile(configFile, data, 0o777)
}
