linters:
  enable:
    - gci
    - gocritic
    - gofumpt
    - misspell

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/testcontainers)

run:
  timeout: 5m
