linters:
  enable:
    - gci
    - gofmt
    - misspell


linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/testcontainers)
    custom-order: true

run:
  timeout: 5m
