site_name: Testcontainers for Go
site_url: https://golang.testcontainers.org
plugins:
    - search
    - codeinclude
    - markdownextradata
theme:
    name: material
    custom_dir: docs/theme
    palette:
        scheme: testcontainers
    font:
        text: Roboto
        code: Roboto Mono
    logo: logo.svg
    favicon: favicon.ico
extra_css:
    - css/extra.css
repo_name: testcontainers-go
repo_url: https://github.com/testcontainers/testcontainers-go
markdown_extensions:
    - admonition
    - codehilite:
        linenums: false
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - toc:
        permalink: true
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
    - Home: index.md
    - Quickstart: quickstart.md
    - Features:
        - features/creating_container.md
        - features/files_and_mounts.md
        - features/configuration.md
        - features/networking.md
        - features/garbage_collector.md
        - features/build_from_dockerfile.md
        - features/docker_auth.md
        - features/docker_compose.md
        - features/follow_logs.md
        - features/override_container_command.md
        - features/copy_file.md
        - Wait Strategies:
            - Introduction: features/wait/introduction.md
            - Exec: features/wait/exec.md
            - Exit: features/wait/exit.md
            - Health: features/wait/health.md
            - HostPort: features/wait/host_port.md
            - HTTP: features/wait/http.md
            - Log: features/wait/log.md
            - Multi: features/wait/multi.md
            - SQL: features/wait/sql.md
    - Modules:
        - modules/index.md
        - modules/couchbase.md
        - modules/k3s.md
        - modules/localstack.md
        - modules/mysql.md
        - modules/neo4j.md
        - modules/postgres.md
        - modules/pulsar.md
        - modules/redis.md
        - modules/redpanda.md
        - modules/vault.md
    - Examples:
        - examples/index.md
        - examples/bigtable.md
        - examples/cockroachdb.md
        - examples/consul.md
        - examples/datastore.md
        - examples/firestore.md
        - examples/mongodb.md
        - examples/nats.md
        - examples/nginx.md
        - examples/pubsub.md
        - examples/spanner.md
        - examples/toxiproxy.md
    - System Requirements:
        - system_requirements/index.md
        - system_requirements/docker.md
        - Continuous Integration:
            - system_requirements/ci/aws_codebuild.md
            - system_requirements/ci/bitbucket_pipelines.md
            - system_requirements/ci/circle_ci.md
            - system_requirements/ci/concourse_ci.md
            - system_requirements/ci/dind_patterns.md
            - system_requirements/ci/drone.md
            - system_requirements/ci/gitlab_ci.md
            - system_requirements/ci/tekton.md
            - system_requirements/ci/travis.md
        - system_requirements/using_colima.md
        - system_requirements/using_podman.md
    - Contributing:
        - contributing.md
        - contributing_docs.md
    - Getting help: getting_help.md
edit_uri: edit/main/docs/
extra:
    latest_version: v0.22.0
