name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before submitting a `bug`, please make sure there is no existing issue for the one you encountered.
  - type: input
    id: tc-version
    attributes:
      label: Testcontainers version
      description: Which Testcontainers version are you using?
      placeholder: ex. 0.13.0
    validations:
      required: true
  - type: dropdown
    id: latest-version
    attributes:
      label: Using the latest Testcontainers version?
      description: If you are not using the latest version, can you update your project and try to reproduce the issue? Is it still happening?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: Which Operating System are you using?
      placeholder: e.g. Linux, Windows
    validations:
      required: true
  - type: input
    id: host-arch
    attributes:
      label: Host arch
      description: Which architecture are you using?
      placeholder: e.g. x86, ARM
    validations:
      required: true
  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Which Go version are you using?
      placeholder: e.g. 1.18
    validations:
      required: true
  - type: textarea
    id: docker-version
    attributes:
      label: Docker version
      description: Please run `docker version` and copy and paste the output into this field.
      render: shell
    validations:
      required: true
  - type: textarea
    id: docker-info
    attributes:
      label: Docker info
      description: Please run `docker info` and copy and paste the output into this field.
      render: shell
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide the context and the expected result.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. The content will be automatically formatted as code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Any links or references to have more context about the issue.

        Tip: You can attach a minimal sample project to reproduce the issue or provide further log files by clicking into this area to focus it and then dragging files in.
