
# Create a new index
POST http://localhost:7700/indexes
Content-Type: application/json
Authorization: Bearer my-master-key

{
  "uid": "movies",
  "primaryKey": "movie_id"
}

###

# Retrieve documents from the 'movies' index
GET http://localhost:7700/indexes/movies/documents
Authorization: Bearer my-master-key

###

# Add a document to the 'movies' index
PUT http://localhost:7700/indexes/movies/documents
Authorization: Bearer my-master-key
Content-Type: application/json

[
  {
    "movie_id": 1212,
    "title": "American Ninja 5",
    "poster": "https://image.tmdb.org/t/p/w1280/iuAQVI4mvjI83wnirpD8GVNRVuY.jpg",
    "overview": "When a scientist's daughter is kidnapped, American Ninja attempts to find her, but this time he teams up with a youngster he has trained in the ways of the ninja.",
    "release_date": 725846400
  }
]

###

# Retrieve a specific document from the 'movies' index
GET http://localhost:54711/indexes/movies/documents/1212
Authorization: Bearer my-master-key
Content-Type: application/json

###

# Retrieve the status of a specific task
GET http://localhost:7700/tasks/17
Authorization: Bearer my-master-key

###

# Create a new dump
POST http://localhost:7700/dumps
Authorization: Bearer my-master-key
