name: Modules generator pipeline

on:
  push:
    paths-ignore:
    - 'mkdocs.yml'
    - 'docs/**'
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'mkdocs.yml'
    - 'docs/**'
    - 'README.md'

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  test-modulegen:
    strategy:
      matrix:
        go-version: [1.19.x, 1.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    env:
      TESTCONTAINERS_RYUK_DISABLED: "false"
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: modVerify
        working-directory: modulegen
        run: go mod verify

      - name: Run module generator tests
        working-directory: modulegen
        run: go build

      - name: Run module generator tests
        working-directory: modulegen
        run: make test-unit

      - name: Test Summary
        uses: test-summary/action@4ee9ece4bca777a38f05c8fc578ac2007fe266f7
        with:
          paths: "**/TEST-*.xml"
        if: always()
