name: Reaper-Off pipeline

on:
  push:
    paths-ignore:
    - 'mkdocs.yml'
    - 'docs/**'
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'mkdocs.yml'
    - 'docs/**'
    - 'README.md'

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  test-reaper-off:
    strategy:
      matrix:
        go-version: [1.19.x, 1.x]
    runs-on: ubuntu-latest
    env:
      TESTCONTAINERS_RYUK_DISABLED: "true"

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: gotestsum
        # only run tests on linux, there are a number of things that won't allow the tests to run on anything else
        # many (maybe, all?) images used can only be build on Linux, they don't have Windows in their manifest, and
        # we can't put Windows Server in "Linux Mode" in Github actions
        # another, host mode is only available on Linux, and we have tests around that, do we skip them?
        run: make test-unit

      - name: Run checker
        run: |
          ./scripts/check_environment.sh

      - name: Test Summary
        uses: test-summary/action@4ee9ece4bca777a38f05c8fc578ac2007fe266f7
        with:
          paths: "**/TEST-*.xml"
        if: always()
