name: Pubsub example pipeline

on: [push, pull_request]

jobs:
  test-pubsub:
    strategy:
      matrix:
        go-version: [1.18.x, 1.x]
    runs-on: "ubuntu-latest"
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: modVerify
        working-directory: ./examples/pubsub
        run: go mod verify

      - name: modTidy
        working-directory: ./examples/pubsub
        run: make tools-tidy

      - name: gotestsum
        working-directory: ./examples/pubsub
        run: make test-unit

      - name: Run checker
        run: |
          ./scripts/check_environment.sh

      - name: Test Summary
        uses: test-summary/action@4ee9ece4bca777a38f05c8fc578ac2007fe266f7
        with:
          paths: "**/TEST-pubsub*.xml"
        if: always()
