name: Sonar Bulk Operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        type: choice
        options:
          - createAll
          - deleteAll

jobs:
  bulk-operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Execute Bulk Operation
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          chmod +x .github/scripts/sonar-manager.sh
          .github/scripts/sonar-manager.sh -a "${{ inputs.operation }}"
